<?php

require 'fbsdk/facebook.php';

//initialize facebook object
$facebook = new Facebook(array(
                           'appId'  => '145439352170764',
                           'secret' => '27cfc1e11bdb9e63f9479edd91cf5599',
                          'fileUpload' => true, 
                           'cookie' => true,));
$facebook->setFileUploadSupport(true);  

//get the base64 data from POST arguments
$b64	=	$_POST['data'];

//remove this "data:image/png;base64" header from the base64 data
$clean	=	substr($b64, 22);

//replace blanks(generated by toDataURL()) with pluses for base64_decode to work correct
$clean = str_replace(' ','+',$clean);

//decode the raw data and save it in a file
$FILE_PATH = $_POST['uid'] . '.png';
file_put_contents($FILE_PATH, base64_decode($clean));

//post the saved file to FB
$args	=	array('message' => '');
$args['image']	=	'@' . realpath($FILE_PATH);
$data = $facebook->api('/me/photos', 'post', $args);

unlink($FILE_PATH);

?>